name: CI

on: [ push, pull_request ]

jobs:
  build:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macOS-latest ]
        node-version: [ 12.x, 10.x ]
    steps:
    - name: Checkout from repository
      uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile --audit --non-interactive
    - name: Run tests
      run: yarn test
    - name: Lint
      run: yarn lint

  deploy:
    needs: [ build ]
    name: Deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout from repository
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Install dependencies
      run: yarn install --frozen-lockfile --non-interactive

    - name: Module bundling
      run: yarn run bundle:prod

    - name: Generate coverage report
      run: yarn test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@master
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: latest
    #     path: dist/

    - name: Login to Docker Hub
      run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD docker.io
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to Heroku Container Registry
      run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD registry.heroku.com
      env:
        DOCKER_USERNAME: _
        DOCKER_PASSWORD: ${{ secrets.HEROKU_API_KEY }}

    - name: Build container
      run: docker build -t eserozvataf/acikkaynak-website:latest -t registry.heroku.com/acikkaynak/web:latest .

    - name: Push to Docker Hub
      run: docker push eserozvataf/acikkaynak-website:latest

    - name: Push to Heroku
      run: docker push registry.heroku.com/acikkaynak/web:latest

    - name: Heroku Release
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:release web --app acikkaynak
